target 'MVVMNews' do

  pod 'Masonry', '~>1.0.1'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'MJExtension', '~> 3.0.13'
  pod 'CocoaLumberjack', '~> 2.3.0'
  pod 'MBProgressHUD', '~> 0.9'
  pod 'Shimmer', '~> 1.0.0'
  pod 'FlatUIKit', '~> 1.6.2'
  pod 'CYLTabBarController', '~> 1.6.0'
  pod 'BmobSDK', '~> 1.7.2'
  pod 'SDWebImage', '~> 3.8.1'
  pod 'TPKeyboardAvoiding', '~> 1.3'

end
